### ISSUE TITLE
new items

### ISSUE THREAD

**Issue by Spydawg** [Leo450/betterbags-gearfirst#1]
New Items not working with this

**Comment by JourneyOver** [comment]
> New Items not working with this

Are you talking about the "Recent items" category? I just tested this and it looks to be working fine on my end.

**Comment by Spydawg** [comment]
Does it add recent items to top spot in list *top of bags*?

I didn't check if it was lower in bags..  not home atm to check..

**Comment by JourneyOver** [comment]
Yep, it adds the recent items category as the very first category if you have that category enabled and then it'll go either gear after or hearthstone (if you have a hearthstone category) and then gear after depending on which option you enable.

**Comment by Spydawg** [comment]
ok I'll check when i get home
