### ISSUE TITLE
Lua Error for BetterBags 

### ISSUE THREAD

**Issue by erobird** [Leo450/betterbags-gearfirst#10]
1x BetterBags_GearFirst/i18n.lua:192: attempt to call method 'S' (a nil value)
[string "@BetterBags_GearFirst/i18n.lua"]:192: in main chunk

Locals:
BetterBags = <table> {
 isBCC = false
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 _bindingFrame = Frame {
 }
 defaultModuleState = false
 name = "BetterBags"
 baseName = "BetterBags"
 orderedModules = <table> {
 }
 backpackShouldClose = false
 isRetail = true
 backpackShouldOpen = false
 atBank = false
 Bags = <table> {
 }
 enabledState = true
 atWarbank = false
 isClassic = false
 hooks = <table> {
 }
 isCata = false
 _buttons = <table> {
 }
}
L = <table> {
 data = <table> {
 }
 modules = <table> {
 }

**Comment by Leo450** [comment]
Fixed in 1.0.11
