### ISSUE TITLE
Off-hand

### ISSUE THREAD

**Issue by Krekot** [Leo450/betterbags-gearfirst#2]
Hello

Off hands are not sorted :)

![Bez tytułu](https://github.com/Leo450/betterbags-gearfirst/assets/580730/15dc3ea2-2af3-4708-9d79-21c434124254)

![image](https://github.com/Leo450/betterbags-gearfirst/assets/580730/cc050d96-4a03-4c38-86d5-395ebef44b46)

**Comment by Leo450** [comment]
Thanks for reporting.
Should be fixed in 1.0.6.
