### ISSUE TITLE
Classic (SOD) - "Main Hand" Category is not sorting to top as the other gear categories

### ISSUE THREAD

**Issue by fysickz** [Leo450/betterbags-gearfirst#6]
Hi - in classic SOD version with this plugin the "Main Hand" Category is not sorting to top as the other gear categories. Not sure if this is intended or not, but would be nice if that category also showed first.

Thanks for this addon btw! Really like this mod :)

Added screenshot for ref:

![image](https://github.com/user-attachments/assets/3f047a64-221b-466f-90e6-371dd36a2918)

**Comment by Leo450** [comment]
Hi mate, thanks for the PR.
I added support for main hand in v1.0.9, same code as yours but with translations for other language :)

Sorry it took that long i was taking a break from the game before TWW.

**Comment by fysickz** [comment]
Amazing! Thanks for your work and support!
